Repository chatty-potato/1take.server, pull requests merged in 2024-10, with the labels that each got.

#78 :sparkles: Interview Custom Exception 구현
  src/main/java/potato/onetake/domain/Ineterview/exception/.gitkeep
  src/main/java/potato/onetake/domain/Ineterview/exception/InterviewErrorCode.java
  src/main/java/potato/onetake/domain/Ineterview/exception/InterviewException.java
  src/main/java/potato/onetake/domain/Ineterview/service/InterviewService.java
  src/main/java/potato/onetake/global/exception/ExceptionHandlerController.java
Labels: enhancement

#81 :recycle: auth 도메인을 최상단 infrastructure폴더로 리펙토링
  src/main/java/potato/onetake/infrastructure/auth/Auth.java
  src/main/java/potato/onetake/infrastructure/auth/CustomOauth2UserService.java
  src/main/java/potato/onetake/infrastructure/auth/cookie/CookieShop.java
  src/main/java/potato/onetake/infrastructure/config/SecurityConfig.java
  src/main/java/potato/onetake/infrastructure/jwt/JwtTokenProvider.java
Labels: refactoring, Security

#93 :lock: modified redis config
  src/main/java/potato/onetake/global/config/RedisConfig.java
Labels: Security, :ambulance: fix

#97 🔒 fix JwtTokenProvider 에서 UserDetailsService bean 문제 해결
  src/main/java/potato/onetake/domain/member/dao/MemberRepository.java
  src/main/java/potato/onetake/domain/member/domain/Member.java
  src/main/java/potato/onetake/infrastructure/auth/AuthRepository.java
  src/main/java/potato/onetake/infrastructure/jwt/CustomUserDetailsService.java
  src/main/java/potato/onetake/infrastructure/jwt/JwtTokenProvider.java
Labels: Security, :ambulance: fix

#99 uuid를 Auth에서 Member 엔티티로 이동
  src/main/java/potato/onetake/infrastructure/auth/Auth.java
  src/main/java/potato/onetake/infrastructure/auth/CustomOauth2UserService.java
Labels: Security, :ambulance: fix
